/* eslint-disable prettier/prettier */
// Do not modify this file, auto generated by AppManifestsPlugin.
import type { ProjectManifest } from '@pnpm/types';

import manifest0 from '/Users/apple/Workspace/micro-app-module-federation-template/micro/login/package.json';

export const appManifests = {
  '@micro/login': manifest0
} satisfies Record<IMicroAppName, ProjectManifest>;